src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VilleRepository::class)]
class Ville
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(options:['unsigned'=>true])]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nom = null;

    #[ORM\Column(length: 10)]
    private ?string $code_postal = null;

    #[ORM\OneToMany(mappedBy: 'ville', targetEntity: Lieu::class)]
    private Collection $lieu;

    public function __construct()
    {
        $this->lieu = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection<int, Lieu>
     */
    public function getLieu(): Collection
    {
        return $this->lieu;
    }

    public function addLieu(Lieu $lieu): self
    {
        if (!$this->lieu->contains($lieu)) {
            $this->lieu->add($lieu);
            $lieu->setVille($this);
        }

        return $this;
    }

    public function removeLieu(Lieu $lieu): self
    {
        if ($this->lieu->removeElement($lieu)) {
            // set the owning side to null (unless already changed)
            if ($lieu->getVille() === $this) {
                $lieu->setVille(null);
            }
        }

        return $this;
    }
}

src/Controller/SortiesController.php
<?php

namespace App\Controller;


use App\Entity\Etats;
use App\Entity\Lieu;
use App\Entity\Participants;
use App\Entity\Sites;
use App\Entity\Sorties;;
use App\Form\FormTypeSortiesType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\equalToIgnoringCase;


#[IsGranted('ROLE_USER')]
class SortiesController extends AbstractController
{
    #[Route('/sorties', name: 'app_sorties')]
    public function index(): Response
    {
        return $this->render('sorties/MonProfil.html.twig', [
            'controller_name' => 'SortiesController',
        ]);
    }

    #[Route('/AddSortie', name: 'app_sorties')]
    public function AddSortie(Request $request,EntityManagerInterface $entityManager): Response
    {
        //instancie une nouvelle sortie
        $sortie= new Sorties();

        //on lui ajoute l'organisateur à savoir l'utilisateur actuellement connecté
        $organisateur=$this->getUser();
        $sortie->setOrganisateur($organisateur);

        //on lui ajoute le site de rattachement
        $idSite=$organisateur->getSite();
        $site=$entityManager->getRepository(Sites::class)->findOneBy(['id'=>$idSite]);
        $sortie->setSite($site);

        //création du formulaire
        $form= $this->createForm(FormTypeSortiesType::class,$sortie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $action=$_POST['action'];
            $nomLieu=$_POST['lieu'];

            $req="";
            switch ($action) {
                case "Enregistrer":
                    $req = "Créee";
                    break;
                case "Publier":
                    $req = "Ouverte";
                    break;
                case "Annuler":
                    return $this->redirectToRoute('app_home');
                    break;
            }


            $etat=$entityManager->getRepository(Etats::class)->findOneBy(['libelle' => $req]);

            $lieu=$entityManager->getRepository(Lieu::class)->findOneBy(['nom'=>$nomLieu]);

            //ajout de l'etat
            $sortie->setEtat($etat);
            $sortie->setLieu($lieu);

            $entityManager->persist($sortie);

            //Validation de la transaction
            $entityManager->flush();

            //Message de confirmation
            $this->addFlash('success', 'Votre sortie a été ajoutée avec succès !');

            //Redirection sur la page de détails
            return $this->redirectToRoute('app_home', [

            ]);
        }
        return $this->render('sorties/AddSortie.html.twig', [
            'sortie'=> $sortie,
            'formSortie' => $form->createView(),

        ]);
    }

    #[Route('/sortie/{id}', name: 'app_details', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function details(int $id, EntityManagerInterface $entityManager): Response
    {
        $sortie = $entityManager->getRepository(Sorties::class)->findOneBy(['id' => $id]);

        //Récup les participants en fonction de la sortie
        $participants = $sortie->getParticipe();

        return $this->render('sorties/details.html.twig', [
            'sortie'=> $sortie,
            'participants' => $participants,
        ]);
    }

    #[Route('/annuler/{id}', name: 'app_annuler_sortie', requirements: ['id' => '\d+'], methods: ['POST','GET'])]
    public function annuler(int $id, EntityManagerInterface $entityManager,Request $request): Response
    {
        $sortie = $entityManager->getRepository(Sorties::class)->findOneBy(['id' => $id]);
        $motif = $request->request->filter('motif',null,FILTER_SANITIZE_STRING);

        if(!empty($motif)){
            $etat = $entityManager->getRepository(Etats::class)->findOneBy(['id' => 6]);

            $sortie->setMotifAnnulation($motif);
            $sortie->setEtat($etat);
            $entityManager->persist($sortie);
            $entityManager->flush();
            $this->addFlash('success', 'Votre sortie a été annulée !');
        }
        return $this->render('sorties/annuler.html.twig', [
            'sortie'=> $sortie,
        ]);
    }
    #[Route('/publier/{id}', name: 'app_publier', requirements: ['id' => '\d+'], methods: ['POST','GET'])]
    public function publier(int $id, EntityManagerInterface $entityManager): Response
    {
        $sortie = $entityManager->getRepository(Sorties::class)->findOneBy(['id' => $id]);
        $etat = $entityManager->getRepository(Etats::class)->findOneBy(['id' => 2]);
        $sortie->setEtat($etat);
        $entityManager->persist($sortie);
        $entityManager->flush();
        $this->addFlash('success', 'La sortie est publiée !');

        return $this->redirectToRoute('app_home');
    }
    #[Route('/modifier/{id}', name: 'app_modifier_sortie', requirements: ['id' => '\d+'], methods: ['POST','GET'])]
    public function modifier(int $id, EntityManagerInterface $entityManager,Request $request): Response
    {
        $sortie = $entityManager->getRepository(Sorties::class)->findOneBy(['id' => $id]);
        $form= $this->createForm(FormTypeSortiesType::class,$sortie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $action=$_POST['action'];
            $nomLieu=$_POST['lieu'];

            $req="";
            switch ($action) {
                case "Enregistrer":
                    $req = "Créee";
                    break;
                case "Publier":
                    $req = "Ouverte";
                    break;
                case "Supprimer":
                    $entityManager->remove($sortie);
                    $entityManager->flush();
                    $this->addFlash('success', 'La sortie a été supprimée !');
                    return $this->redirectToRoute('app_home');
                    break;
                case "Annuler":
                    return $this->redirectToRoute('app_home');
                    break;
            }

            $etat = $entityManager->getRepository(Etats::class)->findOneBy(['libelle' => $req]);
            $lieu = $entityManager->getRepository(Lieu::class)->findOneBy(['nom'=>$nomLieu]);

            $sortie->setEtat($etat);
            $sortie->setLieu($lieu);

            // dd($sortie);
            $entityManager->persist($sortie);

            //Validation de la transaction
            $entityManager->flush();

            //Message de confirmation
            $this->addFlash('success', 'Votre sortie a été modifiée !');

            //Redirection sur la page de détails
            return $this->redirectToRoute('app_home', [

            ]);
        }
        return $this->render('sorties/modifier.html.twig', [
            'sortie'=> $sortie,
            'formSortie' => $form->createView(),

        ]);
    }

}

templates/sorties/AddSortie.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Ajouter une sortie{% endblock %}

{% block h1 %}Ajouter une sortie{% endblock %}

{% block body %}


    {% form_theme formSortie 'bootstrap_5_layout.html.twig' %}
    {{ form_start(formSortie) }}

    <div class="row">
        <!--a gauche-->
        <div class="col">

            {{ form_row(formSortie.nom) }}
            {{ form_row(formSortie.dateHeureDebut) }}
            {{ form_row(formSortie.dateLimiteInscription) }}
            {{ form_row(formSortie.nbInscriptionMax) }}
            {{ form_row(formSortie.duree) }}
            {{ form_row(formSortie.infosSortie) }}

        </div>
        <!--à droite-->
        <div class="col">
            <div>
                <label>Ville Organisatrice</label>
                <input type="text" id="ville" required="required" class="form-control" disabled value="{{ sortie.site.nom }}">
            </div>

            {{ form_row(formSortie.ville) }}

            {# champ de saisie inputNomLieu #}
            <div class="form-group">
                <label for="selectNomLieu">Lieu</label>
                <select class="form-select" id="selectNomLieu" name="lieu">
                </select>
            </div>

            <div>
                <label>Rue</label>
                <input type="text" id="rue" required="required" class="form-control">
            </div>
            <div>
                <label>Code postal</label>
                <input type="text" id="CodePostal" required="required" class="form-control" value="" disabled>
            </div>
            <div>
                <label>Latitude</label>
                <input type="text" id="latitude" class="form-control">
            </div>
            <div>
                <label>Longitude</label>
                <input type="text" id="longitude"  class="form-control">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="text-center">
                <input type="submit" class="customBTNyellow d-inline-block" value="Enregistrer" name="action">

                <input type="submit" class="customBTN d-inline-block" value="Publier" name="action">

                <button onclick="location.href='{{ path('app_home') }}'" class="customBTNred d-inline-block" name="action">Annuler</button>
            </div>
        </div>
    </div>

    {{ form_end(formSortie) }}

{% endblock %}

{% block script %}
    <script>
        /* sur changement de la données dans la liste deroulante de ville ...*/
        $(document).on('change', '#form_type_sorties_ville', function () {
            /* chargement des lieux de la ville concernée */
          chargerCP();
          chargerLieux();
        })
        $(document).on('change', '#selectNomLieu', function () {
            /* chargement des des infos concernant le lieu selectionné */
            chargerInfosLieu();
        })

        /* fonction permettant de recuperer le code postal en fonction de la ville selectionnée */
        function chargerCP(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheCodePostal", /* appel de la fonction rechercheLieuByVille du controlleur AjaxController*/
                data: {
                     'ville_id' :$('#form_type_sorties_ville').val() //recupération de l'id de la ville dans la data
                }
            }).done(function (response) {
                $('#CodePostal').html(''); //initialisation de du code postal

                $('#CodePostal').val(response);
            })
        }

        /* fonction permettant de recuperer le code postal en fonction de la ville selectionnée */
        function chargerLieux(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheLieux",
                data: {
                    'ville_id' : $('#form_type_sorties_ville').val() //recupération de la ville dans la data
                }
            }).done(function (response) {
                let selectElement= $('#selectNomLieu');
                selectElement.html('');
                for(let i = 0 ; i < response.length ; i++) {
                    let lieu = response[i];
                    let option = $('<option value="'+ lieu.nom +'">'+lieu.nom+'</option>');
                    selectElement.append(option);
                }
                $('#rue').val(response[0].rue);
                $('#latitude').val(response[0].latitude);
                $('#longitude').val(response[0].longitude);
            })
        }

        function chargerInfosLieu(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheInfosLieux",
                data: {
                    'lieu_nom' : $('#selectNomLieu').val() //recupération de la ville dans la data
                }
            }).done(function (response) {
                console.log(response);
                $('#rue').val(response.rue);
                $('#latitude').val(response.latitude);
                $('#longitude').val(response.longitude);
            })
        }
    </script>
{% endblock %}

templates/sorties/annuler.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - {{ sortie.nom }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="d-flex justify-content-center align-items-center container">
            <div class="col-auto">
                    <h1>Annuler la sortie : {{ sortie.nom }}</h1>
                    {% for label, messages in app.flashes() %}
                        {% for message in messages %}
                            <div class="alert alert-{{ label }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <p>Nom de la sortie : {{ sortie.nom }}</p>
                    <p>Date et heure : {{ sortie.dateHeureDebut|date('d/m/y H:i') }} </p>
                    <p>Ville organisatrice : {{ sortie.site.nom }}</p>
                    <p>Lieu : {{ sortie.lieu.nom }}</p>
                    <form method="post">
                        <label for="motif">Motif d'annulation :</label><br>
                        <textarea name="motif" id="motif"  rows="5" cols="33" required {% if sortie.etat.libelle =="Annulée" %} disabled {% endif %} placeholder="{{ sortie.motifAnnulation }}"></textarea>
                        <br><br>
                        <div class="d-flex justify-content-between">
                            {% if sortie.etat.libelle !="Annulée" %}
                                <input type="submit" class="customBTN" value="Enregistrer" name="action">
                                <a class="customBTN" href="{{ path('app_home') }}">Annuler</a>
                            {% else %}
                                <a class="customBTN" href="{{ path('app_home') }}">Accueil</a>
                            {% endif %}
                        </div>
                    </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/sorties/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - {{ sortie.nom }}{% endblock %}

{% block h1 %} Détails de la sortie : {{ sortie.nom }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-sm-around">
            <div class="row">
                <div class="col-sm">
                    <p>Nom de la sortie : {{ sortie.nom }}</p>
                    <p>Date et heure : {{ sortie.dateHeureDebut|date('d/m/y H:i') }} </p>
                    <p>Date limite d'inscription : {{ sortie.dateLimiteInscription|date('d/m/y') }}</p>
                    <p>Nombre de places : {{ sortie.participe|length }}/{{ sortie.nbInscriptionMax }}</p>
                    <p>Durée : {{ sortie.duree }} heures</p>
                    <p>Description et infos : {{ sortie.infosSortie }}</p>
                </div>
                <div class="col-sm">
                    {% if (sortie.participe.contains(app.user)) or (app.user.roles[0] =="ROLE_ADMIN") or (sortie.organisateur == app.user)%}
                        <div class="organisateur">
                            <p class="orga">Organisateur :</p>
                            <p>
                                <form action="{{ path('app_profil') }}" method="POST" class="organisateur_display">
                                    <input type="hidden" name="id" value="{{ sortie.organisateur.id }}" />
                                    <button type="submit" class="btn btn-link" >{{ sortie.organisateur.pseudo }}</button>
                                </form>
                            </p>
                        </div>
                    {% else %}
                    <p>Organisateur : {{ sortie.organisateur.pseudo }}</p>
                    {% endif %}
                    <p>Ville organisatrice : {{ sortie.site.nom }}</p>
                    <p>Lieu : {{ sortie.lieu.nom }}</p>
                    <p>Rue : {{ sortie.lieu.rue }}</p>
                    <p>Code postal : {{ sortie.lieu.ville.codePostal }}</p>
                    <p>Latitude : {{ sortie.lieu.latitude }}</p>
                    <p>Longitude : {{ sortie.lieu.longitude }}</p>
                </div>
            </div>
        </div>
    </div>


    <div class="container participants">

        {% if participants is not empty %}

            <h2>Liste des participants</h2>

            <div class="tableau_sorties table-responsive">
                <table class="table table-striped">

                    <thead>
                        <tr>
                            <th scope="col">Pseudo</th>
                            <th scope="col">Nom</th>
                        </tr>
                    </thead>

                    <tbody>
                    {% for participant in participants %}
                        <tr>
                            {% if (sortie.participe.contains(app.user)) or (app.user.roles[0] =="ROLE_ADMIN") or (sortie.organisateur == app.user)%}

                                <td>
                                    <form action="{{ path('app_profil') }}" method="POST">
                                        <input type="hidden" name="id" value="{{ participant.id }}" />
                                        <button type="submit" class="btn btn-link" >{{ participant.pseudo }}</button>
                                    </form>
                                </td>
                                <td>{{ participant.nom }} {{ participant.prenom }}</td>
                            {% else %}
                                <td>{{ participant.pseudo }}</td>
                                <td>{{ participant.nom }} {{ participant.prenom }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        {% else %}
            <p>Aucun participant inscrit pour le moment.</p>
        {% endif %}
        <a class="customBTN" href="{{ path('app_home') }}">Accueil</a>
    </div>

{% endblock %}

templates/sorties/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SortiesController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1>Hello {{ controller_name }}! ✅</h1>
    </div>

{% endblock %}

templates/sorties/modifier.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Modifier la sortie {{ sortie.nom }}{% endblock %}

{% block h1 %}Modifier la sortie {{ sortie.nom }}{% endblock %}

{% block body %}


    {% form_theme formSortie 'bootstrap_5_layout.html.twig' %}
    {{ form_start(formSortie) }}

    <div class="row">
        <!--a gauche-->
        <div class="col">

            {{ form_row(formSortie.nom) }}
            {{ form_row(formSortie.dateHeureDebut) }}
            {{ form_row(formSortie.dateLimiteInscription) }}
            {{ form_row(formSortie.nbInscriptionMax) }}
            {{ form_row(formSortie.duree) }}
            {{ form_row(formSortie.infosSortie) }}

        </div>
        <!--à droite-->
        <div class="col">
            <div>
                <label>Ville Organisatrice</label>
                <input type="text" id="ville" required="required" class="form-control" disabled value="{{ sortie.site.nom }}">
            </div>

            {{ form_row(formSortie.ville) }}

            {# champ de saisie inputNomLieu #}
            <div class="form-group">
                <label for="selectNomLieu">Lieu</label>
                <select class="form-select" id="selectNomLieu" name="lieu">
                </select>
            </div>

            <div>
                <label>Rue</label>
                <input type="text" id="rue" required="required" class="form-control">
            </div>
            <div>
                <label>Code postal</label>
                <input type="text" id="CodePostal" required="required" class="form-control" value="" disabled>
            </div>
            <div>
                <label>Latitude</label>
                <input type="text" id="latitude" class="form-control">
            </div>
            <div>
                <label>Longitude</label>
                <input type="text" id="longitude"  class="form-control">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="text-center">
                <input type="submit" class="customBTN d-inline-block" value="Enregistrer" name="action">

                <input type="submit" class="customBTN d-inline-block" value="Publier" name="action">

                <input type="submit" class="customBTNred d-inline-block" value="Supprimer" name="action">

                <a href="{{ path('app_home') }}" class="customBTNred d-inline-block">Annuler</a>
            </div>
        </div>
    </div>

    {{ form_end(formSortie) }}

{% endblock %}

{% block script %}
    <script>
        /* sur changement de la données dans la liste deroulante de ville ...*/
        $(document).on('change', '#form_type_sorties_ville', function () {
            /* chargement des lieux de la ville concernée */
            chargerCP();
            chargerLieux();
        })
        $(document).on('change', '#selectNomLieu', function () {
            /* chargement des des infos concernant le lieu selectionné */
            chargerInfosLieu();
        })

        /* fonction permettant de recuperer le code postal en fonction de la ville selectionnée */
        function chargerCP(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheCodePostal", /* appel de la fonction rechercheLieuByVille du controlleur AjaxController*/
                data: {
                    'ville_id' : $('#form_type_sorties_ville').val() //recupération de l'id de la ville dans la data
                }
            }).done(function (response) {
                $('#CodePostal').html(''); //initialisation de du code postal

                $('#CodePostal').val(response);
            })
        }

        /* fonction permettant de recuperer le code postal en fonction de la ville selectionnée */
        function chargerLieux(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheLieux",
                data: {
                    'ville_id' : $('#form_type_sorties_ville').val() //recupération de la ville dans la data
                }
            }).done(function (response) {
                let selectElement= $('#selectNomLieu');
                selectElement.html('');
                for(let i = 0 ; i < response.length ; i++) {
                    let lieu = response[i];
                    let option = $('<option value="'+ lieu.nom +'">'+lieu.nom+'</option>');
                    selectElement.append(option);
                }
                $('#rue').val(response[0].rue);
                $('#latitude').val(response[0].latitude);
                $('#longitude').val(response[0].longitude);
            })
        }

        function chargerInfosLieu(){
            jQuery.ajax({
                method: "GET",
                url: "/sortir/public/ajax/rechercheInfosLieux",
                data: {
                    'lieu_nom' : $('#selectNomLieu').val() //recupération de la ville dans la data
                }
            }).done(function (response) {
                console.log(response);
                $('#rue').val(response.rue);
                $('#latitude').val(response.latitude);
                $('#longitude').val(response.longitude);
            })
        }
    </script>
{% endblock %}